### ISSUE TITLE
docker override breaks docker

### ISSUE THREAD

**Issue by neilhwatson** [OldCrowEW/ansible-dcos-common#1]
The settings below prevent Docker from starting

https://github.com/OldCrowEW/ansible-dcos-common/blob/master/templates/override.conf.j2

See 
https://github.com/docker/docker/issues/27661

**Comment by OldCrowEW** [comment]
Feel free to PR the fix.

**Comment by OldCrowEW** [comment]
Per DC/OS [doc](https://dcos.io/docs/1.8/administration/installing/custom/system-requirements/install-docker-centos/)
